spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:ezpt_test
    username: ezpt
    password: ezpt1234
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect:
        format_sql: true
    defer-datasource-initialization: true

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-i45ab.pub-cdb.ntruss.com:3306/ezpt_schema?useSSL=false&allowPublicKeyRetrieval=true
    username: ezpt_dev
    password: ezpt@1234!
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
